### ISSUE TITLE
[meta] issue Data to display with Internal UI

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/internal_ui#1]
This is a meta list of the data that should be included in the team Internal UI Streamlit app. 

- [ ] #2

@dantravers, feel free to add a description of the data you'd like the  Internal UI to display. I've converted the task above to an issue, but feel free to just add bullet points here with a description, and I can convert each point to an issue later.

**Comment by rachel-labri-tipton** [comment]
hey @peterdudfield, I opened up this issue this week for the `internal_ui`. 
Are there other stats you'd like to see visualized by the UI that we could add to the list above? 

I didn't make a PR for the code I pushed yesterday since I'm just working on the main branch for the moment, but I got a bar chart and line graph to display for the MAE for a given time range. 
It looks something like this for the moment:
<img width="1511" alt="Screenshot 2023-04-05 at 17 25 30" src="https://user-images.githubusercontent.com/86949265/230128469-2a04e2dd-6deb-430e-b389-2883a9b9f467.png">

Some of the numbers need fixing, but is this sort of what you were thinking in terms of a dashboard?

**Comment by peterdudfield** [comment]
Yea that looks amazing!!!!

**Comment by dantravers** [comment]
That looks great!  Thanks
I was discussing with Peter today about the forecast horizon - what horizon is that for?  And.... can you make it configurable - I.e. in the nav bar on the left?

**Comment by peterdudfield** [comment]
I would add the forecast horizon next, but not before getting this live and being able to view it
