### ISSUE TITLE
Build docker container and EB app to deploy internal ui

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/internal_ui#3]
## Detailed Description
I would like to deploy the internal ui using docker and elastic beanstalk. 

[This](https://docs.streamlit.io/knowledge-base/tutorials/deploy/docker) article might be helpful with that. 

And [this article](https://discuss.streamlit.io/t/howto-streamlit-on-aws-with-elastic-beanstalk-and-docker/10353) goes into using docker and EB to deploy a Streamlit app. 

I've never used docker or created an EB app before, so will need to figure out the following to begin with:  

1) a little bit more about what building a docker container entails
2) how to create the Dockerfile itself and build the docker image/ container. 
3) identify if I need two containers for this project and possibly two beanstalk apps, one for the data deployed from the database and one for the streamlit code

[Here](https://github.com/hackcollective/wind-curtailment/blob/main/Dockerfile) is an example Dockerfile for a Streamlit app that Peter gave me to start. 

## Context
The internal ui runs locally but needs to be deployed. 

## Possible Implementation
Set up the appropriate docker and EB infrastructure to deploy the app so the team can access it.

**Comment by peterdudfield** [comment]
@devsjc you might need to expose port 8501 in the terraform code here https://github.com/openclimatefix/ocf-infrastructure/blob/development/terraform/modules/services/internal_ui/security_group.tf#L9

Or you can make sure the port is `80` when deploying this streamlit app

**Comment by devsjc** [comment]
I've got this in the eb docker compose 

```
    ports:
      - 80:8501
```

so it should be coming through on 80 in the end?

**Comment by peterdudfield** [comment]
you might know more than me, I something get confused which way round to put it,but looks right. you can rule it out for sure if you change it all to 80, but totally up to you

**Comment by devsjc** [comment]
I've got it "working" without changing ports, had to add "--browser.ServerAddress=0.0.0.0" to the entrypoint. It defaults to localhost otherwise: https://docs.streamlit.io/library/advanced-features/configuration
