### ISSUE TITLE
Add password

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/internal_ui#4]
## Detailed Description
Good to add a password to the streamlit app

## Context
- keep things safe, slightly sensitive info

## Possible Implementation
- make password a github secret
- write password in `Onepassword`
- https://discuss.streamlit.io/t/how-to-set-login-password-for-my-streamlit-app/13150/5
- Future could use `Auth0`

**Comment by devsjc** [comment]
Resolved with commit https://github.com/openclimatefix/internal_ui/commit/db3761ae798ad3a453833a0ad1020eff32624037
